force-app/main/default/objects/Student_Data__c/Student_Data__c.object-meta.xml
<CustomObject>
    <label>Student Data</label>
    <nameField>
        <label>Student Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Data__c/fields/Roll_No__c.field-meta.xml
<CustomField>
    <fullName>Roll_No__c</fullName>
    <label>Roll No</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Data__c/fields/Year_Of_Studying__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Studying__c</fullName>
    <label>Year Of Studying</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentController.cls
public with sharing class StudentController {
@AuraEnabled(cacheable=true)
public static List<Student_Data__c> getName(){
return[SELECT Name,Year_Of_Studying__c ,Roll_No__c  FROM Student_Data__c ORDER BY CreatedDate DESC];
    }
    
@AuraEnabled
public static Student_Data__c Create(String name, String mail, String rollno,string year ){
Student_Data__c stu = new Student_Data__c (Name= name,Roll_No__c= rollno, Year_Of_Studying__c= year, Email__c =mail );
Insert stu;
return stu;
}
@AuraEnabled
public Static void deletestudent(ID studentId){
delete [SELECT Id FROM Student_Data__c WHERE Id = :studentId LIMIT 1];
}
        
    }