force-app/main/default/objects/Admission__c/Admission__c.object-meta.xml
<CustomObject>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Admission__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Admissions</relationshipLabel>
    <relationshipName>Admissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudentAdmissionController.cls
public class StudentAdmissionController {
public Student__c student { get; set; }
public Admission__c admission { get; set; }
public StudentAdmissionController() {
student = new Student__c();
admission = new Admission__c();
}
public PageReference saveDetails() {
try {
insert student;
admission.Student__c = student.Id;
insert admission;
ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Admissionsuccessful.'));
} catch (Exception e) {
ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
}
return null;
}
}