force-app/main/default/objects/Books__c/Books__c.object-meta.xml
<CustomObject>
    <label>Books</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Books__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <label>ISBN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Books__c/fields/Price_Of_The_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Of_The_Book__c</fullName>
    <label>Price Of The Book</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BookLWCController.cls
public class BookLWCController {
    @AuraEnabled
    public static Id bookcreate(String name, string author, string isbn, Decimal price,
        Integer copies,
        Date purchasedDate)
        {
            Books__c book=new Books__c(Name=name, Author__c =author, Available_Copies__c = copies, ISBN__c=isbn, Price_Of_The_Book__c = price, Purchased_Date__c = purchasedDate );
             insert book;
            return book.id;
        }

}