force-app/main/default/objects/ELECTRONICPRODUCT__c/ELECTRONICPRODUCT__c.object-meta.xml
<CustomObject>
    <label>ELECTRONICPRODUCT</label>
    <nameField>
        <label>ELECTRONICPRODUCT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ELECTRONICPRODUCTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddProductController.cls
public class AddProductController {
public String productName { get; set; }
public Decimal productPrice { get; set; }
public String message { get; set; }
    public void AddProductController(){}

 public void saveProduct() {
  if (String.isNotBlank(productName) && productPrice != null) {
      ELECTRONICPRODUCT__c  newProduct = new ELECTRONICPRODUCT__c (
           Name__c = productName,
            price__c = productPrice
         );
            insert newProduct;
            message = 'Product added successfully!';
            productName = '';
            productPrice = null;
        } else {
            message = 'Please enter both product name and price.';
        }
    }
}