force-app/main/default/objects/ELECTRONICPRODUCT__c/ELECTRONICPRODUCT__c.object-meta.xml
<CustomObject>
    <label>ELECTRONICPRODUCT</label>
    <nameField>
        <label>ELECTRONICPRODUCT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ELECTRONICPRODUCTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/pricedesp__c.field-meta.xml
<CustomField>
    <fullName>pricedesp__c</fullName>
    <label>pricedesp</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Activity.cls
public class Activity {
    public void run(){
        List<ELECTRONICPRODUCT__c> elelist= [SELECT price__c FROM ELECTRONICPRODUCT__c ];
        for(ELECTRONICPRODUCT__c i:elelist){
            if(i.price__c<=500){
                i.pricedesp__c='LOW';
            }
            else if(i.price__c>=501 && i.price__c<=1000){
                i.pricedesp__c='MEDIUM';
                }
            else {
                i.pricedesp__c='HIGH';
            }
        }
        update elelist;
    }
    

}