force-app/main/default/objects/ELECTRONICPRODUCT__c/ELECTRONICPRODUCT__c.object-meta.xml
<CustomObject>
    <label>ELECTRONICPRODUCT</label>
    <nameField>
        <label>ELECTRONICPRODUCT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ELECTRONICPRODUCTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ELECTRONICPRODUCT__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ELEPRODUCT.cls
public class ELEPRODUCT {
    public void run(){
        
        List<ELECTRONICPRODUCT__c> elelist= new List<ELECTRONICPRODUCT__c> {
            new ELECTRONICPRODUCT__c(Name= 'firstproduct' ,Name__c ='prod1', price__c= 9000),
			new ELECTRONICPRODUCT__c(Name= 'secondproduct' ,Name__c ='prod2', price__c= 5000),
            new ELECTRONICPRODUCT__c(Name= 'thirdproduct' ,Name__c ='prod3', price__c= 2000)};
            
    
    Insert elelist;
        
        List<ELECTRONICPRODUCT__c> updatelist = new list<ELECTRONICPRODUCT__c> ();
        for(ELECTRONICPRODUCT__c i: updatelist){
            if(i.price__c >= 9000){
                i.price__c=7000;
                updatelist.add(i);
            }
        }
    
update updatelist;
    }
}